### ISSUE TITLE
example segfault

### ISSUE THREAD

**Issue by rtbo** [rtbo/rust-xcb#1]
both example [screen_info](https://github.com/rtbo/rust-xcb/blob/rustc-1.5/examples/screen_info.rs) and [basic_window](https://github.com/rtbo/rust-xcb/blob/rustc-1.5/examples/basic_window.rs) segfault in call to xcb_screen_next
When using directly the unsafe API however, it works (see example [unsafe_screen_info](https://github.com/rtbo/rust-xcb/blob/rustc-1.5/examples/unsafe_screen_info.rs))
I tracked it down to the fact that the ffi setup struct is deep copied in the wrapper struct, and therefore we pass another address to xcb_setup_roots_iterator.
XCB simply refuse that we pass it a pointer to setup that it did not provide, even if all fields are the same

=> make a wrapper that stores a pointer and apply it where necessary (all returned pointer from XCB?)

**Comment by rtbo** [comment]
/cc @Aatch @laumann

I adapted Aatch source base to rustc-1.5 (stable API) and noticed only after that laumann did the same quite in the same time!
I checked your code and you introduced almost same changes as I. I did not manage to keep lifetime in iterators (didn't know the phantom field trick, but it introduces many warnings)
also laumann, you did not include macros.rs in your repo

**Comment by laumann** [comment]
I'm getting the same segfault, but did not figure out why...

You're right, I forgot `macros.rs` - for now I just grabbed your version of (I used `from_raw_parts`, but your version seems a little safer)

**Comment by laumann** [comment]
I tried running `unsafe_screen_info`, but am running into the following problem

```
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/tj/rust/rust-xcb/target/debug/examples/unsafe_screen_info.0.o" "-o" "/home/tj/rust/rust-xcb/target/debug/examples/unsafe_screen_info" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/tj/rust/rust-xcb/target/debug" "-L" "/home/tj/rust/rust-xcb/target/debug/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/tj/rust/rust-xcb/target/debug/libxcb-58c4a70ea6d2fc4e.rlib" "/home/tj/rust/rust-xcb/target/debug/deps/liblibc-c9bdc12d8fb6b7ac.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-71b07a99.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-71b07a99.rlib" "-l" "xcb" "-l" "X11" "-l" "X11-xcb" "-l" "xcb-composite" "-l" "xcb-damage" "-l" "xcb-dpms" "-l" "xcb-dri2" "-l" "xcb-glx" "-l" "xcb-randr" "-l" "xcb-record" "-l" "xcb-render" "-l" "xcb-screensaver" "-l" "xcb-shape" "-l" "xcb-shm" "-l" "xcb-sync" "-l" "xcb-xevie" "-l" "xcb-xf86dri" "-l" "xcb-xfixes" "-l" "xcb-xinerama" "-l" "xcb-xinput" "-l" "xcb-xprint" "-l" "xcb-xtest" "-l" "xcb-xv" "-l" "xcb-xvmc" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "compiler-rt"
note: /usr/bin/ld: cannot find -lxcb-composite
/usr/bin/ld: cannot find -lxcb-damage
/usr/bin/ld: cannot find -lxcb-dpms
/usr/bin/ld: cannot find -lxcb-record
/usr/bin/ld: cannot find -lxcb-screensaver
/usr/bin/ld: cannot find -lxcb-xevie
/usr/bin/ld: cannot find -lxcb-xf86dri
/usr/bin/ld: cannot find -lxcb-xinerama
/usr/bin/ld: cannot find -lxcb-xinput
/usr/bin/ld: cannot find -lxcb-xprint
/usr/bin/ld: cannot find -lxcb-xtest
/usr/bin/ld: cannot find -lxcb-xv
/usr/bin/ld: cannot find -lxcb-xvmc
collect2: error: ld returned 1 exit status
```

which I'll dig into a little more. On Ubuntu it seems these libs are named with an extra `.0` in /usr/lib/x86_64-linux-gnu/

**Comment by laumann** [comment]
This is so weird - I cannot find libxcb-xinput anywhere. All the others seem to be there, but xinput is not even in the Ubuntu repositories (I'm on trusty)

**Comment by rtbo** [comment]
ah yeah, by default the script writes the safe bindings for all extensions, so there is code calling the ffi functions hence requiring to link against those. if it's a bother to install the C extension libraries, just delete the src/[ext].rs files. Ideally they should be completely excluded from this crate and have separate crates for extensions that are not completely obsolete.

regarding xinput, it's not included in APT (I use mint). I built XCB with --enable-xinput. as said, just delete the files that bother you.

**Comment by laumann** [comment]
Ah ok, maybe this is a usecase for cargo features?

I removed xinput, and can successfully run `connect.rs`, but not `screen_info.rs` (am getting a "signal: 11" error). Not really sure where to go from here...

**Comment by rtbo** [comment]
screen_info is still crashing for the reason in the issue description.
_unsafe_screen_info_ does not. the key is to give to  xcb_setup_roots_iterator the same pointer that was obtained by xcb_get_setup

**Comment by laumann** [comment]
Ah! Of course you are right, thanks :smile:

I'll be happy to help in any way with the lifetime definitions if you want...

**Comment by rtbo** [comment]
yeehaa! starting on 477ad1f696ed3c26d5872f7db97b9c5c8be37a6a, all examples run without segfault

[XCB doc](http://xcb.freedesktop.org/PublicApi/#index7h2) says that xcb_get_setup returns a pointer into the connection data, and that it becomes invalid when connection is closed. quite clear what we have to do for Setup lifetime

@laumann please look at how I put lifetime for Setup. I don't know how to tie lifetime of connection to lifetime of setup

for r_client.py, I will introduce an exception for the setup obj, as I think it is an actual exception

**Comment by laumann** [comment]
Awesome! It seems to work (lifetime specifiers look fine) - you didn't commit any updates to `r_client.py`? I ran update.sh, and all the wonderful changes to Setup disappeared and this nasty message appeared:

```
src/base.rs:114:13: 114:27 error: transmute called with differently sized types: *mut ffi::xproto::setup (64 bits) to xproto::Setup (320 bits) [E0512]
src/base.rs:114             mem::transmute(setup)
                            ^~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `xcb`.
```
I'm wondering if it shouldn't wrap pointers from XCB by default, instead of handling setup explicitly? Maybe the answer to that will present itself down the road.

I started playing with including `randr.rs` and ran into a problem with `ffi::base::connection` - randr.rs also declares a `pub type connection` (`= c_uint`), and it seems clear that `ffi::base::connection` could just as well be called `ffi::base::xcb_connection`. Working off your branch, I've got the changes here: fb2ca9835fb2202f6a85a645ecca80f638f17be0

**Comment by rtbo** [comment]
I'm currently writing the modification to r_client.py
I will also move away `SetupIterator` and `ffi::setup_iterator`. this makes no sense. there is no function returning `xcb_setup_iterator_t` in the native API.

as for the ffi names, each struct has the xcb_[name]_t name pattern in the C API. I'd vote to give the ffi interface the same names than in the original libxcb

my plan:
  - fix r_client.py to generate StructPtr compatible code for Setup (and close this issue)
  - change struct names (separate commit)
  - evaluate need for more StructPtr wrappers

**Comment by laumann** [comment]
Cool, there are iterators in the XCB API though, right? I'm looking at https://github.com/jonls/redshift/blob/master/src/gamma-randr.c#L102 and trying to get something similar to work in Rust.

I agree on the FFI names - there could be more name collisions lurking by changing the names of the structs (I have a suspicion that that is why some of the modules in xcb.rs are commented out)

**Comment by rtbo** [comment]
I'm definitely keeping iterators. Only wants to remove the particular SetupIterator. It's not meaningful.
