### ISSUE TITLE
Xft support?

### ISSUE THREAD

**Issue by codic12** [rtbo/rust-xcb#102]
Any way to draw antialiased text? This is done on X11 usually with Xft, which doesn't work natively with xcb so the X11 compatibility header has to be used for it; not sure how to do equivalent with rust-xcb.

**Comment by rtbo** [comment]
I don't know `Xft`. I think it is an antic technology to render text server-side.
If it is not in the XCB headers, there is nothing `rust-xcb` can do about it: these are bindings to XCB.
All modern applications render text client side: render the glyph into an image and present it to the screen.
This is what GUI toolkits such as Qt or Gtk or also Web browsers are doing under the hood.
It is a highly complex topic if you want to do it right.

**Comment by codic12** [comment]
Xft is just an interface to freetype. I'll look into how to do it manually, then. Thanks.

**Comment by rtbo** [comment]
OK I see. I may have confused with Xfont (server side font system).
Be aware that the `x11` crate has an `xft` module, so you already have the bindings there.
Then you can mix `x11 `and `xcb` code using the `xlib_xcb` feature of `rust-xcb`.
This what I do in the [opengl_window](https://github.com/rtbo/rust-xcb/blob/master/examples/opengl_window/main.rs) example. (there is no opengl interface to XCB)
