### ISSUE TITLE
Make functions return a Result instead of panicking?

### ISSUE THREAD

**Issue by sector-f** [rtbo/rust-xcb#11]
Some functions (such as [this](http://rtbo.github.io/rust-xcb/src/xcb/base.rs.html#271) and [this](http://rtbo.github.io/rust-xcb/src/xcb/base.rs.html#349)) call `panic!()` if X isn't running. Wouldn't it make more sense to have these functions return a Result?

**Comment by rtbo** [comment]
I guess so. It will rather be `Option` if the only indication is a null pointer.
I'll have a look on this.

**Comment by rtbo** [comment]
I lacked reading the xcb doc. The `xcb_connect*` functions always return a valid object and error should be checked with `xcb_connection_has_error`.
I will use this to return a `Result`
