### ISSUE TITLE
Lack of consistency in naming checked/unchecked functions

### ISSUE THREAD

**Issue by sector-f** [rtbo/rust-xcb#15]
@panicbit found that "there are 159 occurences of `_checked(` and 88 occurences of `_unchecked(`." It seems to me that standardization would be nice: 

1. All unchecked functions being of the form `foo()` with their checked variants being of the form `foo_checked()`
2. All unchecked functions being of the form `foo_unchecked()` with their checked variants being of the form `foo()`
3. All unchecked functions being of the form `foo_unchecked()` with their checked variants being of the form `foo_checked()`

Personally, I recommend the third option. Standardizing this is going to require a major version increment regardless of the choice, and going with that option will prevent any existing code from suddenly having an unchecked function replaced with a checked one.

**Comment by rtbo** [comment]
my `xproto.rs` has 80 occurrences of `_unchecked` (I guess you included `std::str::from_utf8_unchecked`) and 160 occurrences of `_checked`.
That is 40 bindings of `_unchecked` and 80 bindings of `_checked` because each also have the FFI call.

`xproto.h` has 80 occurrences of both.
I meant to replicate the C API. I apparently got wrong somewhere.

**Comment by sector-f** [comment]
Any reason why the C API is inconsistent?

**Comment by rtbo** [comment]
Yes. Here is a comment in c_client.py
```py
    # Four stunningly confusing possibilities here:
    #
    #   Void            Non-void
    # ------------------------------
    # "req"            "req"
    # 0 flag           CHECKED flag   Normal Mode
    # void_cookie      req_cookie
    # ------------------------------
    # "req_checked"    "req_unchecked"
    # CHECKED flag     0 flag         Abnormal Mode
    # void_cookie      req_cookie
    # ------------------------------
```
`_checked` functions are only for void requests and `_unchecked` functions for non-void requests.
Function names without suffix are for the normal mode. void requests are normally unchecked, and non-void requests are normally checked.
Each request is generated in normal mode and in the "abnormal" mode.

**Comment by rtbo** [comment]
After further check, `xproto.h` has 40 _`unchecked` occurrences within comments.
So it seems that the bindings are consistent with the C API.
I'm closing the issue. Do not hesitate to comment if you feel the topic needs further discussion.

**Comment by sector-f** [comment]
Heh, I was actually about to close it myself.

Perhaps this distinction should be pointed out in the docs somewhere.

**Comment by rtbo** [comment]
Yes. XCB creators themselves described this as confusing.
I may add a general description of XCB and explain this.
