### ISSUE TITLE
How to find Visualtype?

### ISSUE THREAD

**Issue by kandeshvari** [rtbo/rust-xcb#16]
Hi,

I'm trying to use Cairo surface in xcb window. I need to get Visualtype from chain of iterators. I write code:

```rust
fn find_visual<'a>(conn: &'a xcb::Connection, visual: xcb_visualid_t) -> Option<Visualtype<'a>> {
    let setup: Setup<'a> = conn.get_setup();
    for screen in setup.roots() {
        let d_iter: DepthIterator = screen.allowed_depths();
        for depth in d_iter {
            for vis in depth.visuals() {
                if visual == vis.visual_id() {
                    println!("Found visual");
                    return Some(vis)
                }
            }
        }
    }
    None
}
```

And call it as:

```rust
let visual = find_visual(&conn, screen.root_visual()).unwrap();
```

but every time got an error:

```
src/main.rs:56:19: 56:24 error: `setup` does not live long enough
src/main.rs:56     for screen in setup.roots() {
                                 ^~~~~
src/main.rs:54:97: 68:2 note: reference must be valid for the lifetime 'a as defined on the block at 54:96...
src/main.rs:54 fn find_visual<'a>(conn: &'a xcb::Connection, visual: xcb_visualid_t) -> Option<Visualtype<'a>> {
src/main.rs:55     let setup: Setup<'a> = conn.get_setup();
src/main.rs:56     for screen in setup.roots() {
src/main.rs:57         let d_iter: DepthIterator = screen.allowed_depths();
src/main.rs:58         for depth in d_iter {
src/main.rs:59             for vis in depth.visuals() {
               ...
src/main.rs:55:45: 68:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 55:44
src/main.rs:55     let setup: Setup<'a> = conn.get_setup();
src/main.rs:56     for screen in setup.roots() {
src/main.rs:57         let d_iter: DepthIterator = screen.allowed_depths();
src/main.rs:58         for depth in d_iter {
src/main.rs:59             for vis in depth.visuals() {
src/main.rs:60                 if visual == vis.visual_id() {
               ...
```

If I remove `return Some(vis)` all compiles fine.

I've asked this question on stackoverflow (http://stackoverflow.com/questions/37387068/does-not-live-long-enough-error-when-calling-roots-from-rust-xcb) and got an answer that problem in incorrect lifetimes in rust-xcb crate. I've tried to make these changes but got no effect. Could you please help me with this task?

**Comment by kandeshvari** [comment]
I've solved this task. Problem is in unset lifetimes in xcb crate for all functions which returns Iterators. Next lifetime changes in rust-xcb crate allows to compile code successfully:

```rust
impl<'a> Setup<'a> {
    pub fn roots(&self) -> ScreenIterator<'a> {
        unsafe {
             xcb_setup_roots_iterator(self.ptr)
        }
    }
}

impl<'a> Depth<'a> {
    pub fn visuals(&self) -> VisualtypeIterator<'a> {
        unsafe {
            xcb_depth_visuals_iterator(self.ptr)
        }
    }
}

impl<'a> Screen<'a> {
    pub fn allowed_depths(&self) -> DepthIterator<'a> {
        unsafe {
            xcb_screen_allowed_depths_iterator(self.ptr)
        }
    }
}
```

Could you please update rs_client.py script for these changes? I can create PR for these functions only because I don't know nothing about all other. I think all iterators are involved.

**Comment by rtbo** [comment]
@kandeshvari thank you for having worked on this.
The solution given looks correct but it cannot be applied on all iterators. Some types are really value types (no need of lifetime in the iterator) while other have aliasing through pointers and need their lifetime bound.
I pushed 8875772921bcfd672eef8637f74b4f9127b605c2.
I think it is correct (all examples still build) but I didn't test with your code.
I'd be happy to accept a PR with an example of yours with `find_visual` (or modifying an existing one) or otherwise a confirmation that it actually works.

**Comment by rtbo** [comment]
Closing as the lifetime fix is now in [https://github.com/rtbo/rust-xcb/tree/v0.7.4](v0.7.4).
Please reopen if the lifetime fix is somehow incorrect
