### ISSUE TITLE
send_event(_checked) should not take &str

### ISSUE THREAD

**Issue by talchas** [rtbo/rust-xcb#17]
This really wants to be &T to match similar things (change/get property). I suppose this is technically a complaint at the xcb xml files, since they specify char here for no good reason when other places use void*, which would give the &T behavior, but while that was harmless in C, it is a pain here.

**Comment by rtbo** [comment]
In fact this is already addressed in the repo, but was not pushed to crates.io. see 19b4e44b43b9ff7c24e7c0f4ed8661720c1a064e

**Comment by talchas** [comment]
Ahah, so it was, I must have forgotten to double-check the repo as well as the cargo source.

**Comment by rtbo** [comment]
now pushed also in `crates.io` in `0.7.4`
