### ISSUE TITLE
How to draw to root window?

### ISSUE THREAD

**Issue by sector-f** [rtbo/rust-xcb#18]
I'm trying to draw an image to the root window ("set the background image").

I have the correct ID of the root window as a `u32` (or `xcb_window_t`, same thing). I have an image's pixels as a `Vec<u8>`, obtained via the image crate's `raw_pixels` function.

So, how do I actually draw the image to the window? I made an educated guess (based on the hsetroot program's code) but I couldn't get it to work.

Update: I was told in the #xcb channel on Freenode that the correct way of doing this in C is using the `xcb_change_window_attributes` function with  `XCB_CW_BACK_PIXMAP` as the value mask. However, the equivalent function in the binding expects the mask and value as a `(u32, u32)`. Should I convert the `Vec<u8>` to a `u32` somehow? Is this even possible? Or is this not the correct function anyways?

**Comment by rtbo** [comment]
I followed the code posted at SO [here](http://stackoverflow.com/a/28125170) to build example [draw_root_window.rs](https://github.com/rtbo/rust-xcb/blob/master/examples/draw_root_window.rs).
It doesn't have any effect in the main window, but works in another environment like suggested in the SO answer:
``` sh
$ Xephyr -br -noreset -screen "1024x640" :1&
$ DISPLAY=:1.0 cargo run --example draw_root_window
```

**Comment by sector-f** [comment]
>It doesn't have any effect in the main window

Why is that, though? And what's the fix?

One of the comments on SO says "Desktop managers or programms like feh for example, use the pixmap of the root window in order to set the wallpaper," which is making me wonder if this is the wrong approach

**Comment by rtbo** [comment]
a pixmap must be created with
```rust
let pixmap = conn.generate_id();
xcb::create_pixmap(...);
```
I don't know exactly how it must be filled with data, but you can look at the package `xcb-util-image`, which contain such function (e.g. `xcb_create_pixmap_from_bitmap_data`). You can either translate the code from `xcb-util-image` into rust, or create an FFI binding to this function that takes an `u8` pointer as bitmap data. (I don't know what exact format is expected).

Once you have the pixmap id, the call to `xcb::change_window_attributes` becomes trivial.

This is beyond the scope of `rust-xcb`, so I'm going to close the issue. There are many packages around xcb (like `xcb-util`, `xcb-icccm` etc.) that can be the subject of seperate binding crates.
