### ISSUE TITLE
XCB ICCCM is missing

### ISSUE THREAD

**Issue by meh** [rtbo/rust-xcb#19]
Unless I'm blind, it would help to get `xcb_icccm.h` wrapped as well, so size hints and whatnot can be set on windows.

**Comment by rtbo** [comment]
`rust-xcb` only scopes the main `xcb` package with auto generated code from xml definitions, so `xcb_icccm.h` will not be part of it.
`xcb-icccm` should be made in a separate (probably hand-written) crate. (as should `xcb-util`, `xcb-ewmh`). initiatives are welcome!

**Comment by meh** [comment]
Yeah, makes sense, I think I'll work on an `xcb-util` crate.
