### ISSUE TITLE
Is there a reason the XCB types aren't `Send` and/or `Sync`?

### ISSUE THREAD

**Issue by meh** [rtbo/rust-xcb#23]
I'm having to wrap them every time I want to send the connection and events to another thread, I'm pretty sure XCB was made to be thread-safe in the first place.

Could be wrong tho.

**Comment by rtbo** [comment]
From what I could read on the [XCB mailing list](https://lists.freedesktop.org/archives/xcb/2012-October/007888.html), Xcb is thread safe only if the application links to `pthread`. Otherwise the synchronization primitives called by Xcb ends up to `no-op`.
I'm not sure how to handle that with rust.

**Comment by meh** [comment]
I'm 100% sure libstd links to pthread at least on POSIX systems.

```
> ldd target/release/dux | grep pthread
	libpthread.so.0 => /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0 (0x00007f00e954f000)
```

In any case if `Sync` is not present, at least `Send` should, that's just to send a type across threads, not actual parallel access.

**Comment by meh** [comment]
Also worst case scenario, you could add a `thread` Cargo feature that links in pthread as well, thus ensuring the safety, that way you can optionally implement `Sync` and `Send` and everyone's happy.

**Comment by meh** [comment]
Asked on `#rust`, it's not defined anywhere that libstd **must** link to pthread, so I guess the best way to go would be a feature.

**Comment by rtbo** [comment]
@meh if you have a short sample code with multiple threads, do not hesitate to propose a pull request.

**Comment by meh** [comment]
There are other types that need `Send` and `Sync` for it to be useful, for instance `Error`, `Event` and `Reply`.

Considering they all implement `Drop` themselves and are basically PODs it shouldn't be an issue.

A typical example would be to create a connection, do event registering/initialization and whatever returning any error, then spawning a thread that may send XCB events through a channel for another thread to eat them.

**Comment by meh** [comment]
Implementing them for `Cookie` may also be a good idea to treat them as kind of a promise/future, but I'm not entirely sure on the safety of that, especially the fact it stores a raw pointer to the connection, which may die.

That's probably kind of unsound even in non threaded code tho.

**Comment by rtbo** [comment]
@meh how is this supposed to work?
a connection cannot be cloned so it must be moved to a thread. if so I can only use the connection in one thread?
1. in this case `Sync` is not necessary
2. is there a point to move the connection to another thread without cloning?

**Comment by rtbo** [comment]
I started to make an exemple.
Intention is to send regular events from a thread and let the main loop do as normal.
It doesn't compile because connection is not moved into the thread.
```rust
extern crate xcb;

use std::iter::{Iterator};
use std::{thread, time};

fn main() {
    let (conn, screen_num) = xcb::Connection::connect(None).unwrap();
    let setup = conn.get_setup();
    let screen = setup.roots().nth(screen_num as usize).unwrap();

    let window = conn.generate_id();

    let values = [
        (xcb::CW_BACK_PIXEL, screen.white_pixel()),
        (xcb::CW_EVENT_MASK, xcb::EVENT_MASK_EXPOSURE | xcb::EVENT_MASK_KEY_PRESS |
            xcb::EVENT_MASK_STRUCTURE_NOTIFY | xcb::EVENT_MASK_PROPERTY_CHANGE),
    ];

    xcb::create_window(&conn,
        xcb::COPY_FROM_PARENT as u8,
        window,
        screen.root(),
        0, 0,
        150, 150,
        10,
        xcb::WINDOW_CLASS_INPUT_OUTPUT as u16,
        screen.root_visual(),
        &values);

    xcb::map_window(&conn, window);


    thread::spawn(|| {
        let mut smiley = false;
        loop {
            let title = if smiley {
                "Basic Threaded Window ;-)"
            }
            else {
                "Basic Threaded Window"
            };

            let c = xcb::change_property_checked(&conn, xcb::PROP_MODE_REPLACE as u8, window,
                    xcb::ATOM_WM_NAME, xcb::ATOM_STRING, 8, title.as_bytes());

            if conn.has_error().is_err() || c.request_check().is_err() {
                break;
            }

            smiley = !smiley;
            thread::sleep(time::Duration::from_millis(500));
        }
    });

    conn.flush();

    loop {
        let event = conn.wait_for_event();
        match event {
            None => { break; }
            Some(event) => {
                let r = event.response_type();
                if r == xcb::KEY_PRESS as u8 {
                    let key_press : &xcb::KeyPressEvent = xcb::cast_event(&event);

                    println!("Key '{}' pressed", key_press.detail());

                    if key_press.detail() == 0x18 { // Q (on qwerty)
                        break;
                    }
                }
            }
        }
    }
}
```

**Comment by rtbo** [comment]
I quickly realized that I can use connection in several threads with `Arc`.

What remain open is the concern you have expressed about Cookie

**Comment by rtbo** [comment]
`Cookie` is indeed unsafe at the moment.
It is possible to store a reference to the `Connection` instead of pointer to the FFI struct.
This would bind the `Cookie` lifetime to the `Connection`.
Another possibility is to break the API and require that the connection is passed directly to the cookie method instead of stored into it. eg:
```rust
let cook = xcb::intern_atom(&conn, true, "_NET_WM_STATE");
// this
let atom = cook.get_reply().unwrap().atom();
// would become
let atom = cook.get_reply(&conn).unwrap().atom();
```
The latter solution is simpler and more consistent with the rest of the API.
thoughts?

**Comment by meh** [comment]
A safe and ergonomic solution would be to instead of having the `Connection` drop close and destroy the `xcb_connection_t`, having another kind of `Handle` type or whatever which contains the `xcb_connection_t` and its only job is having a `Drop` implementation that closes it.

Then everything that now contains a `*mut xcb_connection_t` will contain an `Arc<Handle>` in the threaded case and an `Rc<Handle>` in the non-threaded case. Or always an `Arc` to reduce complexity but adding more overhead to the single-threaded case.

This does imply a greater runtime cost, but it would allow effortlessly passing around `Cookie`s.

That said, personally, I do not think I ever stored cookies so far, other than in xcb-util because some types there effectively extend pre-existing cookies, which means the lifetime would end up being the same anyway.

Both ways would technically be breaking changes tho, but it is definitely unsound so I guess they would be required. So yeah, I think binding the cookie on the connection lifetime would work best from a performance/ergonomy perspective.

**Comment by meh** [comment]
On the simpler note about passing the connection to the `get_reply`, that wouldn't work either because you could pass a different `Connection` from the one that created the cookie, which would likely explode in funny ways.

**Comment by rtbo** [comment]
I made Cookie's lifetime bound to Connection.
regarding the Handle type you mention, I don't really get it. Connection can be placed into a Arc, so there is no need for an additional type.

**Comment by meh** [comment]
`QueryExtensionData` seems to have the same unsoundness as the old cookie design, it needs a lifetime parameter bound to the `Connection`.

If you don't know you don't have to pass the `Connection` reference to the struct, you just need it to define it as:

```rust
pub struct QueryExtensionData<'a> {
    ptr: *const xcb_query_extension_reply_t,
    _marker: PhantomData<&'a ()>,
}
```

Then it will just pick up the `'a` from `&self` in `get_extension_data`.

**Comment by meh** [comment]
I'm starting to wonder how useful the `thread` feature actually is, `libstd` currently **always** links in `pthread`, which means XCB will always use the threaded stuff in practice, so there's no way for it to not use it.

Might be a good idea to drop it and always implement them by default.
