### ISSUE TITLE
unresolved import `xcb::randr`

### ISSUE THREAD

**Issue by liftoff** [rtbo/rust-xcb#26]
Trying to build the `examples/randr_screen_info.rs` example results in this error:

    error[E0432]: unresolved import `xcb::randr`
     --> src/main.rs:4:5
      |
    4 | use xcb::randr;
      |     ^^^^^^^^^^ no `randr` in `xcb`

I double-checked that I have all the necessary dev libs (I think):

    $ dpkg -l | grep randr
    ii  libxcb-randr0:amd64                             1.11.1-1ubuntu1                                   amd64        X C Binding, randr extension
    ii  libxcb-randr0-dev:amd64                         1.11.1-1ubuntu1                                   amd64        X C Binding, randr extension, development files
    ii  libxrandr-dev:amd64                             2:1.5.0-1                                         amd64        X11 RandR extension library (development headers)
    ii  libxrandr2:amd64                                2:1.5.0-1                                         amd64        X11 RandR extension library
    ii  libxrandr2:i386                                 2:1.5.0-1                                         i386         X11 RandR extension library
    ii  x11proto-randr-dev                              1.5.0-1                                           all          X11 RandR extension wire protocol

Am I missing something?  This is on Ubuntu 16.10

rust-xcb version 0.7.5

**Comment by rtbo** [comment]
This is `rustc` that cannot find `xcb::randr` at compile stage.
It has nothing to do with installed libraries, with which you might only have issues at link stage.

Each `rust-xcb` extension is behind a Cargo `feature` of same name.
You can look at [Cargo.toml](https://github.com/rtbo/rust-xcb/blob/master/Cargo.toml) and [scripts/test_examples.sh](https://github.com/rtbo/rust-xcb/blob/master/scripts/test_examples.sh) to find out about the available features and how to build examples.
I.e. you can build `examples/randr_screen_info.rs` with this command from the `rust-xcb` root dir:
```$ cargo build --example randr_screen_info --features randr```

**Comment by liftoff** [comment]
Thanks.  I figured it out...  Had to put all the "features" I required in my Cargo.toml:

```
[dependencies.xcb]
version = "*"
features = ["shm", "randr", "damage", "xv"]
```

I'm new to rust so I apologize if this is something that should've been obvious.
