### ISSUE TITLE
`randr::NotifyData` is missing an `impl` block, preventing data access without unsafe code

### ISSUE THREAD

**Issue by ibabushkin** [rtbo/rust-xcb#27]
The title pretty much states it all. Is this due to missing code generation (which I could contribute, as I need it myself) or are there some deeper reasons for the missing data accessors?

Update: I'm aware the underlying type, `xcb_randr_notify_data_t` is a simple union around a few types, which can be accessed by simply casting the pointer, but an exported API would be nice nonetheless.

**Comment by ibabushkin** [comment]
I stand corrected: It is *not* possible to obtain, say, a `CrtcChange` from a `NotifyData` in a reasonably safe way, since we can't construct `StructPtr`s from application code (which makes sense, mind you). However, this also means we essentially disallow a lot of proper, senseful code. I will try to provide a proper `impl` block for `NotifyData` and send a PR.

**Comment by ibabushkin** [comment]
I stand corrected: It is *not* possible to obtain, say, a `CrtcChange` from a `NotifyData` in a reasonably safe way, since we can't construct `StructPtr`s from application code (which makes sense, mind you). However, this also means we essentially disallow a lot of proper, senseful code. I will try to provide a proper `impl` block for `NotifyData` and send a PR.

**Comment by rtbo** [comment]
Yes, unions accessors are only implemented for the simplest types. Also all types containing padding are at the moment not considered as POD, which is a mistake, hence the StructPtr. Really, types such as CrtcChange should be POD.

**Comment by rtbo** [comment]
> I will try to provide a proper impl block for NotifyData and send a PR.

Great! Please make sure to test building all extensions with `--features debug_all` (dummy feature that pulls everything in).
Some of them (especially `xkb`) required me to handle many corner cases in `rs_client.py`.

**Comment by ibabushkin** [comment]
I think I can safely close this now, but when do you plan to push the new version to crates.io?

(No hurries, I can use my fork for the time being, just curious).

Cheers.

**Comment by rtbo** [comment]
I have pushed a few commits that may change something for you. What I did is that structs with padding can also be POD. This makes `CtrtcChange` and other structs POD. Please check if it doesn't break anything in your code. 
Otherwise I'm ready to publish to `crates.io`.

**Comment by ibabushkin** [comment]
Alright, I'll do that ASAP.

**Comment by ibabushkin** [comment]
It seems to work fine for me, I've looked at the code, I don't see why it should fail. So I guess you're good to go with publishing.

**Comment by rtbo** [comment]
`xcb-0.7.6` is published
