### ISSUE TITLE
Doesn’t build in recent Nightly, "anonymous bound region BrAnon(0) in return but not args"

### ISSUE THREAD

**Issue by SimonSapin** [rtbo/rust-xcb#40]
See https://github.com/rust-lang/rust/issues/43567.

Adding a lifetime parameter to a few function declarations in `src/ffi/xproto.rs` like this:

```diff
-    pub fn xcb_list_extensions_names_iterator (R: *const xcb_list_extensions_reply_t)
-            -> xcb_str_iterator_t;
+    pub fn xcb_list_extensions_names_iterator<'a> (R: *const xcb_list_extensions_reply_t)
+            -> xcb_str_iterator_t<'a>;
```

… fixes the issue, but that file is `.gitignore`’d and generated. I looked at `rs_client.py` a bit but didn’t find an easy way to make it generate that code.

**Comment by nox** [comment]
@rtbo Could we get an answer on this please?

**Comment by SimonSapin** [comment]
#41 fixes this.

**Comment by rtbo** [comment]
@SimonSapin could you test a37d1fad85167438377d4c0ac91797d8b1f4c26e?
What it does is assigning lifetimes as your 1st comment hereabove.
It builds with nightly.

**Comment by SimonSapin** [comment]
@rtbo I made a "try" build with this branch and all tests pass. Could you publish this as version 0.7.7? Thank you!

**Comment by rtbo** [comment]
done!

**Comment by quininer** [comment]
Can you also publish 0.8.1?

**Comment by rtbo** [comment]
@quininer yes will do.
