### ISSUE TITLE
deterministic builds not published

### ISSUE THREAD

**Issue by metajack** [rtbo/rust-xcb#48]
A commit fixing deterministic builds was committed but a new crate was not published. Can you publish a new version with that so that sccache builds can cache things that depend on xcb?

**Comment by conradkdotcom** [comment]
@rtbo Any news here by any chance ? Would love to have the latest changes in a minor version bump on Crates.io :smiley:

**Comment by rtbo** [comment]
Yes, sorry about that.
It's done now under `v0.8.2`.
