### ISSUE TITLE
vec returned by replies should be owned by replies

### ISSUE THREAD

**Issue by rtbo** [rtbo/rust-xcb#5]
this version of [randr_crtc_info.rs](https://github.com/rtbo/rust-xcb/blob/issue_5/examples/randr_crtc_info.rs#L19-L24) crashes because of this

**Comment by rtbo** [comment]
/cc @laumann

I see that you have forked my repo. I'm happy about it!
don't hesitate to send pull requests!

**Comment by laumann** [comment]
I thought you were on the right path with `StructPtr`, and am starting to think that maybe this is the approach that should be used for all structs returned by XCB.

I see we have once again gone in the same direction, so I have merged your latest master into mine, and pushed [use-features](https://github.com/laumann/rust-xcb/tree/use-features) branch, where I'm hoping to get my randr example running.

**Comment by laumann** [comment]
I'm hoping to eventually reimplement the following: https://github.com/jonls/redshift/blob/master/src/gamma-randr.c#L47-L87 preferably using the wrappers provided in rust-xcb (ie xcb::randr, instead of xcb::ff::randr)

Using the FFI bindings directly does not seem to be a problem, so my hunch is that we need to change r_client.py to use StructPtr in most places, instead of of Struct. We should also implement Drop, to ensure deallocation of C-allocated structs (consider https://github.com/jonls/redshift/blob/master/src/gamma-randr.c#L87 - the `ver_reply` struct is manually deallocated)

**Comment by rtbo** [comment]
FYI, I have made [randr_crtc_info.rs](https://github.com/rtbo/rust-xcb/blob/master/examples/randr_crtc_info.rs) in the master branch that works and do not use FFI. this issue just raise the problem that the lifetime are not correct and can lead to segfault

In the current wrappers, the replies are already stored as pointer with a Drop trait. you can look at [struct Reply<T> in base.rs](https://github.com/rtbo/rust-xcb/blob/master/src/base.rs#L290-L305). Errors are dealt the same way.

I agree that all structs manipulated by pointer in the C API should be wrapped with StructPtr instead of Struct, but I think not all are to be freed. many are held directly by a reply and freed in the same time. While looking at the C code, I have seen replies returning data located in continous memory right after the reply struct itself. In those cases, we need a lifetime tied to the Reply lifetime.
(this is the case for this present issue)

**Comment by rtbo** [comment]
I can't test your example at the moment. Can you tell where it fails and why?
I'm not familiar with randr, but in [randr_crtc_info.rs](https://github.com/rtbo/rust-xcb/blob/master/examples/randr_crtc_info.rs) I call CreateWindow and conn.flush() before calling `GetScreenResources`
That may be the key...

**Comment by laumann** [comment]
That did the trick! There is no (apparent) need for `conn.flush()`

**Comment by rtbo** [comment]
Well, this was more simple than expected, only have to return a slice!
A choice is made here for arrays and strings obtained from replies.
Until now data obtained from replies was owned: String and Vec (Vec being buggy). I am changing this to borrowed data (&str and &[T]) with lifetime of the reply object (which impl Drop)

**Comment by laumann** [comment]
Yay! That allowed me to fix my `randr.rs` example - nicely spotted. I'm thinking `&Vec<T>` should work just as well, but I'm happy either way. Nice work! :+1:

**Comment by rtbo** [comment]
@laumann `&Vec <T>` implies that the actual `Vec<T>` is stored in the reply. The slice returned is reference to data in the C reply. No copy is made

**Comment by laumann** [comment]
You are correct...
