### ISSUE TITLE
failed to run custom build command for xcb v0.8.2 No such command in 2.7.13 of python

### ISSUE THREAD

**Issue by mikhail-krainik** [rtbo/rust-xcb#61]
Hello. Could someone help me to understand what should I do to resolve this error.
I installed `sudo apt install libxcb1-dev` but it didn't help. 
```
error: failed to run custom build command for `xcb v0.8.2`
process didn't exit successfully: `/path/to/project/target/debug/build/xcb-2a2b3010996288d8/build-script-build` (exit code: 101)
--- stdout
No such command in 2.7.13 of python
```

**Comment by rtbo** [comment]
The python build script (`rs_client.py`) relies on Python 3.
That's probably the reason of the failure.

**Comment by mikhail-krainik** [comment]
It is a bit strange to choose a language for an assembly that does not have backward compatibility between versions 2 and 3.
