### ISSUE TITLE
docs.rs build issue

### ISSUE THREAD

**Issue by timvisee** [rtbo/rust-xcb#74]
It seems that `xcb` is causing my [`clipboard-ext`](https://crates.io/crates/clipboard-ext) crate build to fail on `docs.rs`.
Here's the error log: https://docs.rs/crate/clipboard-ext/0.1.0/builds/221309

The `docs.rs` page of `xcb` itself seems to be fine: https://docs.rs/xcb

Any idea what is going on?

**Comment by rtbo** [comment]
The log says `OSError, Read only filesystem`, and blocks code generation. 
It doesn't seem related to rust-xcb.
May be you can retrigger the build?

**Comment by timvisee** [comment]
Thanks for the prompt response.

The error happens in `rs_client.py` which is part of `xcb`. New builds on `docs.rs` fail as well.

I've also had other builds fail on GitLab CI when running `cargo test`. Once because `python3` was missing (is this really required?), and sometimes because of something else I haven't figured out yet.

**Comment by Lompik** [comment]
Try to update to ```0.9```. This is fixed with 026b58ef0ab928e7f01c356fc9dd4ce29bab3c51 . doc.rs's ```src/``` is not writable since 2019-10.

**Comment by timvisee** [comment]
@Lompik Thanks!

It appears that `rust-clipboard` (which I'm using) pulls in an old `xcb` version, causing the issue. I've submitted a [PR](https://github.com/aweinstock314/rust-clipboard/pull/75) to fix this. Though I wonder if it will ever be accepted.

**Comment by Lompik** [comment]
In the meantime, maybe you could use https://github.com/alacritty/copypasta ?

**Comment by timvisee** [comment]
Well, this is for my [`rust-clipboard-ext`](https://github.com/timvisee/rust-clipboard-ext) crate, being an extension for `rust-clipboard`. So it isn't really possible to use something else. Thanks for the tip though!

**Comment by rtbo** [comment]
Already fixed in `v0.9`
