### ISSUE TITLE
Correct way to get the screen's refresh rate?

### ISSUE THREAD

**Issue by crsaracco** [rtbo/rust-xcb#75]
I'm attempting to get the refresh rate of the screen, similar to the info that `xrandr` gives you.

Here's what I have so far (not final API for what I'm doing, but good enough to post here):

```rust
fn refresh_rate(&self) {
    let conn = Application::get_connection();

    let cookie = xcb::randr::get_screen_info(&conn, self.window_id);
    let reply = cookie.get_reply().unwrap();

    let rates = reply.rates();
    for (i, rate) in rates.enumerate() {
        println!("{:?}", rate.rates());
    }
}
```

That println gives me `[50]`, but `xrandr` is giving me 60.00.

Questions:

 - Obviously, first, why is it different? What's the correct way to do it?
 - What units is the result in? I'm surprised it's in `u16`s, instead of something like a float (that `xrandr` is giving me)
 - I saw somewhere else that I might have to call `xcb_randr_query_version` on my connection (major.minor >= 1.1) to get this to work right -- is this the case? I'm doing it as of right now, but I'm not sure if I'm doing it correctly. Also, what's a good major/minor to set here? Any good safe defaults for portability?
 - Is it worth updating `randr_screen_info.rs` to show how to get this information?

Thanks!

**Comment by rtbo** [comment]
Hi,
I don't know exactly how to do it.
Note that I get with `get_screen_info.rates` by extending examples/randr_screen_info.rs seems completely erratic (thousands of fields, most of them are zero ??)
```rust
    let rates = reply.rates();
    for (i, rate) in rates.enumerate() {
        if i != 0 { println!(""); }
        println!("screen {}: {:?}", i+1, rate.rates());
    }
```

Looking at the [source of xrandr](https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/master/xrandr.c), the refresh rate is obtained from `randr::get_screen_resources`, then `modes`.
The actual rate is calculated by [mode_refresh](https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/master/xrandr.c#L576)
