### ISSUE TITLE
advice on converting char to keycode

### ISSUE THREAD

**Issue by yazgoo** [rtbo/rust-xcb#79]
Hi,

Thanks for those bindings.
I'd like to convert a char to a keycode (and also the other way).

Any suggestion on how to do so ?

**Comment by rtbo** [comment]
Hi,
To convert keycode to symbol or char, you need a keymap.
You would need to use xkbcommon library. There are bindings available for Rust.

**Comment by yazgoo** [comment]
Thanks, will try that !
