### ISSUE TITLE
Async / Futures integration

### ISSUE THREAD

**Issue by ratijas** [rtbo/rust-xcb#86]
What are the options to integrate XCB with Rust async infrastructure?

As far as I can tell, there are only `wait_for_event()`, `poll_for_event()` and `poll_for_queued_event()` methods on Connection, all of which take nothing and return `Option<GenericEvent>`. That is clearly not enough to build efficient async wrapper around.

**Comment by rijenkii** [comment]
You can try getting a file descriptor with `xcb_get_file_descriptor` and waiting on it with `mio` or something like that, and when it triggers - try polling, but it looks like there are [some](https://xcb.pdx.freedesktop.narkive.com/qe8fp845/questions-about-proper-event-loop-and-timers) [caveats](https://lists.freedesktop.org/archives/xcb/2015-July/010437.html).

Looking into `libxcb`s source code, you may find something interesting inside `xcb_in.c`, it looks like there's some code that uses `poll` and `select` that might give you some ideas.

**Comment by ratijas** [comment]
Sounds like an interesting challenge. Gotta try one day. Thanks for the directions!
