### ISSUE TITLE
Replace Python build dependency with Rust

### ISSUE THREAD

**Issue by parasyte** [rtbo/rust-xcb#99]
This might sound antagonistic, but it's an honest question. Why is there a 2,500-line Python script running as a build dependency for a Rust crate? The subtext of the question is that Rust is already a Turing-complete general purpose programming language, and should be fully capable of doing everything that Python can do.

I can't build my project on Linux because `xcb` is a transitive dependency. I am forced to install Python 3 in the build environment.

**Comment by parasyte** [comment]
Ok, I believe this is actually an issue when compiling with [`cross`](https://github.com/rust-embedded/cross). It appears the docker images don't have Python 3.

See also #31

**Comment by rtbo** [comment]
The script is in python because it relies on the xcb python library shipped with XCB. 
The script was adapted from the equivalent for the C library, and was quite a nightmare to code. 
I agree it would be better to have a 100% rust program to parse XML and generate the code.
